export const todos = [{
  createdAt: new Date().toLocaleString(),
  id: "1",
  isDone: true,
  title: "test vue",
  updatedAt: new Date().toLocaleString(),
  detail: "This is done now.",
},
{
  createdAt: new Date().toLocaleString(),
  id: "2",
  isDone: true,
  title: "test vue two of a kind",
  updatedAt: new Date().toLocaleString(),
  detail: "Are we still testing?",
},
{
  createdAt: new Date().toLocaleString(),
  id: "3",
  isDone: false,
  title: "Vitest test",
  updatedAt: new Date().toLocaleString(),
  detail: "I wonder the unit testing experience...",
},
{
  createdAt: new Date().toLocaleString(),
  id: "1",
  isDone: true,
  title: "test vue",
  updatedAt: new Date().toLocaleString(),
  detail: "This is done now.",
},
{
  createdAt: new Date().toLocaleString(),
  id: "2",
  isDone: true,
  title: "test vue two of a kind",
  updatedAt: new Date().toLocaleString(),
  detail: "Are we still testing?",
},
{
  createdAt: new Date().toLocaleString(),
  id: "3",
  isDone: false,
  title: "Vitest test",
  updatedAt: new Date().toLocaleString(),
  detail: "I wonder the unit testing experience...",
},
{
  createdAt: new Date().toLocaleString(),
  id: "1",
  isDone: true,
  title: "test vue",
  updatedAt: new Date().toLocaleString(),
  detail: "This is done now.",
},
{
  createdAt: new Date().toLocaleString(),
  id: "2",
  isDone: true,
  title: "test vue two of a kind",
  updatedAt: new Date().toLocaleString(),
  detail: "Are we still testing?",
},
{
  createdAt: new Date().toLocaleString(),
  id: "3",
  isDone: false,
  title: "Vitest test",
  updatedAt: new Date().toLocaleString(),
  detail: "I wonder the unit testing experience...",
},]